spring.application.name=config-server
server.port=8888  
# Puerto típico del Config Server

# Configuración del servidor de configuración
spring.cloud.config.server.git.uri= ${SPRINGCLOUD_CONFIG_SERVER_GIT_URI}
spring.cloud.config.server.git.username= ${GIT_USER}
spring.cloud.config.server.git.password= ${GIT_TOKEN}
spring.cloud.config.server.git.clone-on-start= true
spring.cloud.config.server.git.default-label= master


# Properties for connect to RabbitMQ Server
spring.rabbitmq.host= ${RABBITMQ_HOST}
spring.rabbitmq.port= ${RABBITMQ_PORT}
spring.rabbitmq.username= ${RABBITMQ_USERNAME}
spring.rabbitmq.password= ${RABBITMQ_PASSWORD}

# Habilitar los endpoints de actuator
management.endpoints.web.exposure.include=*



